#ifndef ENUM_H
#define ENUM_H

enum BULLET_TYPE{SLUG,ENUM_BULLET_TYPE_FIN};
enum JET_TYPE{MIG21,F4,F104,HARRIER,ENUM_JET_TYPE_FIN};
enum SPEED{AIRBRAKE,STANDARD,AFTERBURNER};
enum ENEMY_MODE{PATROL,PURSUIT,DOGFIGHT};
enum JET_ABILITY{CMEASURE,DASH,ENUM_JET_ABILITY_FIN};
enum GUN_TYPE{SHVAK,ADEN,GATLING,ENUM_GUN_TYPE_FIN};
enum MSL_TYPE{IR,RAD,ENUM_MSL_TYPE_FIN};
enum JET_STATUS{BURNING,IMMOBILIZED,ENUM_JET_STATUS_FIN};
enum BKGR_TYPE{BERLIN,INDIA,PFERD,ENUM_BKGR_TYPE_FIN};

#endif