#ifndef ENUM_H
#define ENUM_H

enum BULLET_TYPE{SLUG,ENUM_BULLET_TYPE_FIN};
enum JET_TYPE{MIG21,F4,F104,HARRIER,ENUM_JET_TYPE_FIN};
enum BOSS_TYPE{MIG29 = ENUM_JET_TYPE_FIN,SR91,ENUM_BOSS_TYPE_FIN};
enum SPEED{AIRBRAKE,STANDARD,AFTERBURNER};
enum ENEMY_MODE{PATROL,PURSUIT,DOGFIGHT};

enum BOSS_ABILITY{RAND_POS,DASH,CMEASURE,ENUM_BOSS_ABILITY_FIN};

enum GUN_TYPE{SHVAK,ADEN,GATLING,ENUM_GUN_TYPE_FIN};
enum MSL_TYPE{IR,RAD,ENUM_MSL_TYPE_FIN};
enum JET_STATUS{BURNING,IMMOBILIZED,ENUM_JET_STATUS_FIN};
enum MSL_STATUS{CONTROLLED,ENUM_MSL_STATUS_FIN};
enum LVL_TYPE{BERLIN,INDIA,PFERD,ENUM_LVL_TYPE_FIN};
enum PLVL_TYPE{UKRAINE = ENUM_LVL_TYPE_FIN, PACIFIC, ENUM_BKGR_TYPE_FIN};

enum GMODE{MENU,SELECTION,MISSION,MISSION_INIT,QUIT};

#endif